[build]
  command = "echo 'Building...'"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "echo 'Building...'"

[dev]
  port = 3000

# Desabilitar badge do Netlify
[build.environment]
  NETLIFY_USE_YARN = false
